#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuuki Udagawa
# SPDX-License-Identifier: BSD-3-Clause

import sys

user_input_text = sys.stdin.read().strip()

try:
    if not user_input_text:
        print("入力なし")

    non_n_c = True

    for c in user_input_text:
        if c.isalpha():
            non_n_c = False
        break

    if non_n_c:
        raise ValueError("")


    character_count = len(user_input_text)
    word_count = len(user_input_text.split())
    word_list = list(user_input_text.split())

    print("入力された文字数は{}文字、単語数は{}単語です".format(character_count, word_count))

    print("使われた単語")
    for i, word in enumerate(word_list):
        print("{}語目：{}".format(i+1, word))

except ValueError:
    sys.exit(1)
