#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuuki Udagawa
# SPDX-License-Identifier: BSD-3-Clause

import sys

if len(sys.argv) > 1:
    user_input_text = " ".join(sys.argv[1:])
else:
    user_input_text = sys.stdin.read().strip()

if not user_input_text:
    print("入力なし")
else:
    character_count = len(user_input_text)
    word_count = len(user_input_text.split(" "))

    print("入力された文字数は{}です".format(character_count))
    print("入力された単語数は{}です".format(word_count))
